ring-tone: "klingelton.mp3"
ring-volume: 10
# SID tunes have no concept of length
ring-length: 15

message-tone: "ringtone_ringnroll.ogg"
message-volume: 10
# SID tunes have no concept of length
message-length: 3

