#!/bin/bash -e

cd data/themes

for theme in *
do
	if [[ ! -d "$theme" ]]
	then
		continue
	fi

	echo "Compiling theme $theme"

	cd $theme
	data_path="../../themes_data/"$theme"/"

	for filename in *.edc
	do
		/opt/e17/bin/edje_cc -id $data_path/images -fd $data_path/fonts $filename
	done

	cd ..
done
