#!/bin/sh

#copy *.state files from ./scenarios/ to /usr/share/openmoko/scenarios

cp scenarios/*  /usr/share/openmoko/scenarios/
cp oevents/* /etc/freesmartphone/oevents/
cp phone/* /etc/freesmartphone/opreferences/conf/phone/
cp profiles/* /etc/freesmartphone/opreferences/conf/profiles/
cp rules/* /etc/freesmartphone/opreferences/conf/rules/

#auxmenu:
if [ 'ls /usr/share | grep -c "auxmenu"' = "0" ]; then
        mkdir /usr/share/auxmenu
fi
cp auxmenu/auxmenu.py /usr/share/auxmenu/auxmenu.py
cp auxmenu/auxmenu.edj /usr/share/auxmenu/auxmenu.edj
cp auxmenu/auxmenu.sh /usr/bin/auxmenu

exit 1