#!/bin/sh

cp scenarios/*  /usr/share/openmoko/scenarios/
cp oevents/* /etc/freesmartphone/oevents/
cp phone/default.yaml /etc/freesmartphone/opreferences/conf/phone/default.yaml
cp phone/default.yaml /etc/freesmartphone/opreferences/conf/phone/headset.yaml
cp phone/default.yaml /etc/freesmartphone/opreferences/conf/phone/headset_silent.yaml
cp profiles/* /etc/freesmartphone/opreferences/conf/profiles/
cp rules/* /etc/freesmartphone/opreferences/conf/rules/

#auxmenu:
# mkdir -p /usr/share/auxmenu
# 
# cp auxmenu/auxmenu.py /usr/share/auxmenu/auxmenu.py
# cp auxmenu/auxmenu.edj /usr/share/auxmenu/auxmenu.edj
# cp auxmenu/auxmenu.sh /usr/bin/auxmenu

exit 1